services:
  plm_database:
    image: postgres
    container_name: plm_database
    restart: always
    env_file:
      - .env
    environment:
      POSTGRES_DB: ${DATABASE_NAME}
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASS}
    ports:
      - "${DATABASE_PORT}:5432"
    networks:
      - plm_network

volumes:
  plm_data:

networks:
  plm_network:
    driver: bridge
