@baseUrl = http://localhost:9094

### Actuator
GET {{baseUrl}}/actuator
Accept: application/json

### Create a Lender
POST {{baseUrl}}/lenders
Content-Type: application/json

{
  "name": "Alice",
  "phone": "351911195160",
  "bankData": "IBAN:PT503239218390123801",
  "address": "0 Fools Street"
}

### Create transaction #1 BORROW  20
POST {{baseUrl}}/lenders/3a793fb1-8268-4262-b8a7-595e17dec24b/transactions
Content-Type: application/json

{
  "idLender": "3a793fb1-8268-4262-b8a7-595e17dec24b",
  "transactionPaymentType": "MONEY",
  "transactionType": "BORROWED",
  "transactionValue": 20.0
}

### Create transaction #2 BORROW  30
POST {{baseUrl}}/lenders/3a793fb1-8268-4262-b8a7-595e17dec24b/transactions
Content-Type: application/json

{
  "idLender": "3a793fb1-8268-4262-b8a7-595e17dec24b",
  "transactionPaymentType": "MONEY",
  "transactionType": "BORROWED",
  "transactionValue": 30.0
}

### Create transaction #3 BORROW  20
POST {{baseUrl}}/lenders/3a793fb1-8268-4262-b8a7-595e17dec24b/transactions
Content-Type: application/json

{
  "idLender": "3a793fb1-8268-4262-b8a7-595e17dec24b",
  "transactionPaymentType": "MONEY",
  "transactionType": "BORROWED",
  "transactionValue": 20.0
}

### Create transaction #4 PAYED   20
POST {{baseUrl}}/lenders/3a793fb1-8268-4262-b8a7-595e17dec24b/transactions
Content-Type: application/json

{
  "idLender": "3a793fb1-8268-4262-b8a7-595e17dec24b",
  "transactionPaymentType": "MONEY",
  "transactionType": "PAYMENT",
  "transactionValue": 20.0
}

### Cancel transaction #2 CANCEL 20
POST {{baseUrl}}/lenders/3a793fb1-8268-4262-b8a7-595e17dec24b/transactions
Content-Type: application/json

{
  "cancelTransactionId": "e16bbaf7-fd38-4616-bf0e-57707e84efd2",
  "idLender": "3a793fb1-8268-4262-b8a7-595e17dec24b"
}
